#!/usr/bin/env python
"""Generate a complete OpenFOAM case for one Wigley-hull towing condition.

    python tools/gen_case.py --fn 0.316 --level medium --out cases/fn0316

Every dictionary is written from here, so a case is reproducible from one
command and a mesh study is a loop rather than a folder of hand-edits.

Physics: half domain with a symmetry plane on the centreline, free surface
captured with interFoam (VOF), steady state reached by local time stepping
(the same approach as OpenFOAM's own DTC hull tutorial), k-omega SST
turbulence with wall functions.
"""

from __future__ import annotations

import argparse
import math
import os
import shutil

G = 9.81
NU_WATER = 1.09e-6   # m^2/s at 15 C, fresh water (towing tank condition)
NU_AIR = 1.48e-5
RHO_WATER = 999.0
RHO_AIR = 1.0

HEADER = """/*--------------------------------*- C++ -*----------------------------------*\\
| generated by wigley-cfd/tools/gen_case.py                                   |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    object      {obj};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

"""

LEVELS = {
    # base cell size (m), hull surface refinement, free-surface z-refinements
    "coarse": dict(base=0.15, hull=(2, 3), fs_refine=2, fs_band=0.12),
    "medium": dict(base=0.10, hull=(3, 4), fs_refine=3, fs_band=0.12),
    "fine":   dict(base=0.075, hull=(4, 5), fs_refine=3, fs_band=0.10),
}


def w(path, cls, obj, body):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(HEADER.format(cls=cls, obj=obj))
        fh.write(body)
        fh.write("\n\n// ************************************************************************* //\n")


def generate(out, fn, L=3.0, B=0.3, T=0.1875, level="medium", end_iter=3000, n_proc=20,
             stl="cases/hull.stl"):
    cfg = LEVELS[level]
    U = fn * math.sqrt(G * L)

    # -- domain, in metres, hull spans x in [-L/2, +L/2] -------------------
    x0, x1 = -1.25 * L, 2.0 * L
    y0, y1 = 0.0, 1.1 * L
    z0, z1 = -0.7 * L, 0.35 * L

    base = cfg["base"]
    nx = int(round((x1 - x0) / base))
    ny = int(round((y1 - y0) / base))
    nz = int(round((z1 - z0) / base))

    shutil.rmtree(out, ignore_errors=True)
    os.makedirs(f"{out}/constant/triSurface", exist_ok=True)
    shutil.copy(stl, f"{out}/constant/triSurface/hull.stl")

    # ---------------------------------------------------------------- mesh
    w(f"{out}/system/blockMeshDict", "dictionary", "blockMeshDict", f"""
scale   1;

vertices
(
    ({x0} {y0} {z0}) ({x1} {y0} {z0}) ({x1} {y1} {z0}) ({x0} {y1} {z0})
    ({x0} {y0} {z1}) ({x1} {y0} {z1}) ({x1} {y1} {z1}) ({x0} {y1} {z1})
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1)
);

edges ();

boundary
(
    inlet   {{ type patch;    faces ((0 4 7 3)); }}
    outlet  {{ type patch;    faces ((1 2 6 5)); }}
    bottom  {{ type wall;     faces ((0 3 2 1)); }}
    atmosphere {{ type patch; faces ((4 5 6 7)); }}
    symmetry {{ type symmetryPlane; faces ((0 1 5 4)); }}
    side    {{ type patch;    faces ((3 7 6 2)); }}
);
""")

    # free-surface band refinement, in z only: the waves are thin and long,
    # so refining isotropically would be a waste of cells
    band = cfg["fs_band"]
    for i in range(cfg["fs_refine"]):
        h = band / (2 ** i)
        w(f"{out}/system/topoSetDict.{i+1}", "dictionary", "topoSetDict", f"""
actions
(
    {{
        name    fsCells;
        type    cellSet;
        action  new;
        source  boxToCell;
        box     ({x0} {y0} {-h}) ({x1} {y1} {h});
    }}
);
""")
    w(f"{out}/system/refineMeshDict", "dictionary", "refineMeshDict", """
set             fsCells;
coordinateSystem global;
globalCoeffs { tan1 (1 0 0); tan2 (0 1 0); }
directions      ( normal );
useHexTopology  yes;
geometricCut    no;
writeMesh       no;
""")

    hull_min, hull_max = cfg["hull"]
    w(f"{out}/system/snappyHexMeshDict", "dictionary", "snappyHexMeshDict", f"""
castellatedMesh true;
snap            true;
addLayers       false;

geometry
{{
    hull.stl {{ type triSurfaceMesh; name hull; }}
    nearHull
    {{
        type searchableBox;
        min ({-0.75*L} {y0} {-3*T});
        max ({0.9*L} {0.35*L} {2*T});
    }}
}};

castellatedMeshControls
{{
    maxLocalCells       4000000;
    maxGlobalCells      12000000;
    minRefinementCells  10;
    maxLoadUnbalance    0.10;
    nCellsBetweenLevels 3;

    features ( {{ file "hull.eMesh"; level {hull_max}; }} );

    refinementSurfaces
    {{
        hull {{ level ({hull_min} {hull_max}); patchInfo {{ type wall; }} }}
    }}

    resolveFeatureAngle 30;

    refinementRegions
    {{
        nearHull {{ mode inside; levels ((1E15 1)); }}
    }}

    locationInMesh ({x1 - 0.3} {y1 - 0.3} {z1 - 0.3});
    allowFreeStandingZoneFaces true;
}}

snapControls
{{
    nSmoothPatch    3;
    tolerance       2.0;
    nSolveIter      30;
    nRelaxIter      5;
    nFeatureSnapIter 10;
    implicitFeatureSnap false;
    explicitFeatureSnap true;
    multiRegionFeatureSnap false;
}}

addLayersControls
{{
    relativeSizes true;
    layers {{}}
    expansionRatio 1.2;
    finalLayerThickness 0.5;
    minThickness 0.1;
    nGrow 0;
    featureAngle 60;
    nRelaxIter 3;
    nSmoothSurfaceNormals 1;
    nSmoothNormals 3;
    nSmoothThickness 10;
    maxFaceThicknessRatio 0.5;
    maxThicknessToMedialRatio 0.3;
    minMedialAxisAngle 90;
    nBufferCellsNoExtrude 0;
    nLayerIter 50;
}}

meshQualityControls
{{
    maxNonOrtho 65;
    maxBoundarySkewness 20;
    maxInternalSkewness 4;
    maxConcave 80;
    minVol 1e-13;
    minTetQuality 1e-15;
    minArea -1;
    minTwist 0.02;
    minDeterminant 0.001;
    minFaceWeight 0.02;
    minVolRatio 0.01;
    minTriangleTwist -1;
    nSmoothScale 4;
    errorReduction 0.75;
}}

mergeTolerance 1e-6;
""")

    w(f"{out}/system/surfaceFeatureExtractDict", "dictionary", "surfaceFeatureExtractDict", """
hull.stl
{
    extractionMethod    extractFromSurface;
    includedAngle       150;
    subsetFeatures { nonManifoldEdges no; openEdges yes; }
    writeObj            no;
}
""")

    # ------------------------------------------------------------- physics
    w(f"{out}/constant/g", "uniformDimensionedVectorField", "g",
      "dimensions      [0 1 -2 0 0 0 0];\nvalue           (0 0 -9.81);\n")

    w(f"{out}/constant/transportProperties", "dictionary", "transportProperties", f"""
phases (water air);

water
{{
    transportModel  Newtonian;
    nu              {NU_WATER};
    rho             {RHO_WATER};
}}

air
{{
    transportModel  Newtonian;
    nu              {NU_AIR};
    rho             {RHO_AIR};
}}

sigma           0.07;
""")

    w(f"{out}/constant/turbulenceProperties", "dictionary", "turbulenceProperties", """
simulationType  RAS;

RAS
{
    RASModel        kOmegaSST;
    turbulence      on;
    printCoeffs     on;
}
""")

    # --------------------------------------------------------------- fields
    I = 0.01
    k = 1.5 * (U * I) ** 2
    omega = math.sqrt(k) / (0.1 * L) / 0.09 ** 0.25

    def field(obj, dims, internal, entries):
        w(f"{out}/0.orig/{obj}", "volScalarField" if obj not in ("U",) else "volVectorField", obj,
          f"dimensions      {dims};\ninternalField   uniform {internal};\n\nboundaryField\n{{\n{entries}\n}}\n")

    field("alpha.water", "[0 0 0 0 0 0 0]", "0", """
    inlet       { type variableHeightFlowRate; lowerBound 0; upperBound 1; value uniform 0; }
    outlet      { type variableHeightFlowRate; lowerBound 0; upperBound 1; value uniform 0; }
    bottom      { type zeroGradient; }
    atmosphere  { type inletOutlet; inletValue uniform 0; value uniform 0; }
    side        { type zeroGradient; }
    symmetry    { type symmetryPlane; }
    hull        { type zeroGradient; }
""")

    field("U", "[0 1 -1 0 0 0 0]", f"({U} 0 0)", f"""
    inlet       {{ type fixedValue; value uniform ({U} 0 0); }}
    outlet      {{ type outletPhaseMeanVelocity; alpha alpha.water; Umean {U}; value uniform ({U} 0 0); }}
    bottom      {{ type fixedValue; value uniform ({U} 0 0); }}
    atmosphere  {{ type pressureInletOutletVelocity; value uniform (0 0 0); }}
    side        {{ type slip; }}
    symmetry    {{ type symmetryPlane; }}
    hull        {{ type noSlip; }}
""")

    field("p_rgh", "[1 -1 -2 0 0 0 0]", "0", """
    inlet       { type fixedFluxPressure; value uniform 0; }
    outlet      { type fixedFluxPressure; value uniform 0; }
    bottom      { type fixedFluxPressure; value uniform 0; }
    atmosphere  { type totalPressure; p0 uniform 0; }
    side        { type slip; }
    symmetry    { type symmetryPlane; }
    hull        { type fixedFluxPressure; value uniform 0; }
""")

    field("k", "[0 2 -2 0 0 0 0]", f"{k:.6g}", f"""
    inlet       {{ type fixedValue; value uniform {k:.6g}; }}
    outlet      {{ type inletOutlet; inletValue uniform {k:.6g}; value uniform {k:.6g}; }}
    bottom      {{ type kqRWallFunction; value uniform {k:.6g}; }}
    atmosphere  {{ type inletOutlet; inletValue uniform {k:.6g}; value uniform {k:.6g}; }}
    side        {{ type slip; }}
    symmetry    {{ type symmetryPlane; }}
    hull        {{ type kqRWallFunction; value uniform {k:.6g}; }}
""")

    field("omega", "[0 0 -1 0 0 0 0]", f"{omega:.6g}", f"""
    inlet       {{ type fixedValue; value uniform {omega:.6g}; }}
    outlet      {{ type inletOutlet; inletValue uniform {omega:.6g}; value uniform {omega:.6g}; }}
    bottom      {{ type omegaWallFunction; value uniform {omega:.6g}; }}
    atmosphere  {{ type inletOutlet; inletValue uniform {omega:.6g}; value uniform {omega:.6g}; }}
    side        {{ type slip; }}
    symmetry    {{ type symmetryPlane; }}
    hull        {{ type omegaWallFunction; value uniform {omega:.6g}; }}
""")

    field("nut", "[0 2 -1 0 0 0 0]", "0", """
    inlet       { type calculated; value uniform 0; }
    outlet      { type calculated; value uniform 0; }
    bottom      { type nutkWallFunction; value uniform 0; }
    atmosphere  { type calculated; value uniform 0; }
    side        { type slip; }
    symmetry    { type symmetryPlane; }
    hull        { type nutkWallFunction; value uniform 0; }
""")

    w(f"{out}/system/setFieldsDict", "dictionary", "setFieldsDict", f"""
defaultFieldValues ( volScalarFieldValue alpha.water 0 );

regions
(
    boxToCell
    {{
        box ({x0-1} {y0-1} {z0-1}) ({x1+1} {y1+1} 0);
        fieldValues ( volScalarFieldValue alpha.water 1 );
    }}
);
""")

    # -------------------------------------------------------------- control
    w(f"{out}/system/controlDict", "dictionary", "controlDict", f"""
application     interFoam;
startFrom       latestTime;
startTime       0;
stopAt          endTime;
endTime         {end_iter};
deltaT          1;
writeControl    timeStep;
writeInterval   {end_iter};
purgeWrite      2;
writeFormat     binary;
writePrecision  8;
writeCompression off;
timeFormat      general;
timePrecision   6;
runTimeModifiable yes;
adjustTimeStep  no;

functions
{{
    forces
    {{
        type            forces;
        libs            (forces);
        patches         (hull);
        rho             rho;
        log             yes;
        writeControl    timeStep;
        writeInterval   10;
        CofR            (0 0 0);
    }}

    waterLine
    {{
        type            surfaces;
        libs            (sampling);
        writeControl    onEnd;
        surfaceFormat   raw;
        fields          (alpha.water);
        surfaces
        {{
            freeSurface {{ type isoSurfaceCell; isoField alpha.water; isoValue 0.5; interpolate true; }}
        }}
    }}

    yPlus
    {{
        type            yPlus;
        libs            (fieldFunctionObjects);
        writeControl    onEnd;
    }}
}}
""")

    w(f"{out}/system/fvSchemes", "dictionary", "fvSchemes", """
ddtSchemes      { default         localEuler; }

gradSchemes     { default         Gauss linear; }

divSchemes
{
    div(rhoPhi,U)       Gauss linearUpwind grad(U);
    div(phi,alpha)      Gauss vanLeer;
    div(phirb,alpha)    Gauss linear;
    div(phi,k)          Gauss upwind;
    div(phi,omega)      Gauss upwind;
    div(((rho*nuEff)*dev2(T(grad(U))))) Gauss linear;
}

laplacianSchemes { default        Gauss linear corrected; }
interpolationSchemes { default    linear; }
snGradSchemes   { default         corrected; }
wallDist        { method          meshWave; }
""")

    w(f"{out}/system/fvSolution", "dictionary", "fvSolution", """
solvers
{
    "alpha.water.*"
    {
        nAlphaCorr      1;
        nAlphaSubCycles 2;
        cAlpha          1;
        MULESCorr       yes;
        nLimiterIter    5;
        alphaApplyPrevCorr no;
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-8;
        relTol          0;
    }

    "pcorr.*"
    {
        solver          PCG;
        preconditioner  DIC;
        tolerance       1e-5;
        relTol          0;
    }

    p_rgh
    {
        solver          GAMG;
        tolerance       1e-7;
        relTol          0.01;
        smoother        DIC;
    }

    p_rghFinal
    {
        $p_rgh;
        relTol          0;
    }

    "(U|k|omega).*"
    {
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-7;
        relTol          0.1;
    }
}

PIMPLE
{
    momentumPredictor   no;
    nOuterCorrectors    1;
    nCorrectors         2;
    nNonOrthogonalCorrectors 0;

    maxCo               8;
    maxAlphaCo          4;
    rDeltaTSmoothingCoeff 0.05;
    rDeltaTDampingCoeff 0.5;
    nAlphaSpreadIter    0;
    nAlphaSweepIter     0;
    maxDeltaT           1;
}

relaxationFactors { equations { ".*" 1; } }
""")

    w(f"{out}/system/decomposeParDict", "dictionary", "decomposeParDict", f"""
numberOfSubdomains {n_proc};
method          scotch;
""")

    w(f"{out}/system/meshQualityDict", "dictionary", "meshQualityDict",
      '#includeEtc "caseDicts/meshQualityDict"\n')

    with open(f"{out}/case.json", "w") as fh:
        import json
        json.dump(
            dict(fn=fn, U=U, L=L, B=B, T=T, level=level, base=base, end_iter=end_iter,
                 nx=nx, ny=ny, nz=nz, domain=dict(x=[x0, x1], y=[y0, y1], z=[z0, z1]),
                 Re=U * L / NU_WATER, rho=RHO_WATER, nu=NU_WATER),
            fh, indent=2)
    return out


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--fn", type=float, required=True)
    ap.add_argument("--level", default="medium", choices=list(LEVELS))
    ap.add_argument("--out", required=True)
    ap.add_argument("--iters", type=int, default=3000)
    ap.add_argument("--procs", type=int, default=20)
    ap.add_argument("--stl", default="cases/hull.stl")
    a = ap.parse_args()
    print(generate(a.out, a.fn, level=a.level, end_iter=a.iters, n_proc=a.procs, stl=a.stl))
